import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useState } from 'react';
import { Calendar, Users, Rocket, CreditCard } from 'lucide-react';
export default function BookingHistory() {
    const [bookings, setBookings] = useState([]);
    useEffect(() => {
        const savedBookings = JSON.parse(localStorage.getItem('bookings') || '[]');
        setBookings(savedBookings);
    }, []);
    return (_jsxs("div", { className: "max-w-7xl mx-auto p-6", children: [_jsx("h1", { className: "text-3xl font-bold mb-8 gradient-text", children: "Your Space Journeys" }), bookings.length === 0 ? (_jsx("div", { className: "text-center text-gray-400 py-12", children: _jsx("p", { children: "No bookings found. Start your space adventure today!" }) })) : (_jsx("div", { className: "space-y-4", children: bookings.map((booking) => (_jsx("div", { className: "gradient-border p-6", children: _jsxs("div", { className: "flex justify-between items-start", children: [_jsxs("div", { className: "space-y-4", children: [_jsxs("div", { children: [_jsxs("h2", { className: "text-xl font-semibold text-purple-300 mb-2", children: [booking.from, " \u2192 ", booking.to] }), _jsxs("div", { className: "flex items-center space-x-6 text-gray-300", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Rocket, { className: "h-4 w-4 text-purple-400" }), _jsx("span", { children: booking.vehicle })] }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Users, { className: "h-4 w-4 text-purple-400" }), _jsxs("span", { children: [booking.passengers, " passengers"] })] })] })] }), _jsxs("div", { className: "flex items-center space-x-6 text-gray-300", children: [_jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(Calendar, { className: "h-4 w-4 text-purple-400" }), _jsx("span", { children: new Date(booking.journeyDate).toLocaleDateString() })] }), _jsxs("div", { className: "flex items-center space-x-2", children: [_jsx(CreditCard, { className: "h-4 w-4 text-purple-400" }), _jsxs("span", { children: ["$", booking.totalPrice.toLocaleString()] })] })] })] }), _jsxs("div", { className: "flex flex-col items-end", children: [_jsx("span", { className: "bg-purple-500/20 text-purple-300 px-3 py-1 rounded-full text-sm", children: booking.status.charAt(0).toUpperCase() + booking.status.slice(1) }), _jsxs("span", { className: "text-sm text-gray-500 mt-2", children: ["Booked on ", new Date(booking.bookingDate).toLocaleDateString()] })] })] }) }, booking.id))) }))] }));
}
